version: "3"

services:
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs

